// CountryShapes.swift
// GeoExplorer
//
// Loads countryShapes.json (generated by generate_shapes.py) into memory
// and makes it available to both CountryMapView (rendering) and Quiz.swift
// (filtering which countries can appear in the map quiz).
//
// ── Why Foundation-only? ──────────────────────────────────────────────────────
// This file intentionally does NOT import MapKit.  Keeping shape data separate
// from map rendering means Quiz.swift can ask "does this country have a shape?"
// without pulling in the entire MapKit framework.  CountryMapView.swift imports
// MapKit and uses ShapeLoader to build MKPolygon overlays.
//
// ── What is a lazy static property? ──────────────────────────────────────────
// `static let shapes: ...` is initialised the very first time it is accessed —
// not when the app launches.  This is called lazy initialisation.  It means we
// pay the JSON-parsing cost only when the first map quiz question loads, not
// at startup.  Swift guarantees the initialiser runs exactly once, safely, even
// if two threads access the property at the same moment.

import Foundation

// ── Data model ────────────────────────────────────────────────────────────────
// One CountryShape represents a single country in countryShapes.json.
// `polygons` is an array of rings; each ring is an array of [lat, lon] pairs.
// For simple countries (e.g. France mainland) there is one ring.
// For countries with detached territories (e.g. USA with Alaska) there are
// several rings — one per land mass.
struct CountryShape: Decodable {
    let name    : String
    let polygons: [[[Double]]]   // polygons[ring][point][lat/lon index]
}

// ── Shape loader ──────────────────────────────────────────────────────────────
enum ShapeLoader {

    /// Dictionary from country name → CountryShape.
    /// Populated once, lazily, from the bundled countryShapes.json.
    static let shapes: [String: CountryShape] = {
        guard
            let url  = Bundle.main.url(forResource: "countryShapes", withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let list = try? JSONDecoder().decode([CountryShape].self, from: data)
        else {
            return [:]
        }
        // uniquingKeysWith keeps the first entry when two shapes share a name.
        // This prevents a crash if the JSON ever contains a duplicate key
        // (e.g. a disputed territory mistakenly mapped to an existing country).
        return Dictionary(list.map { ($0.name, $0) }, uniquingKeysWith: { first, _ in first })
    }()

    /// Set of country names that have shape data — used in Quiz.swift to
    /// filter the map-quiz question pool down to countries we can display.
    static let shapeNames: Set<String> = Set(shapes.keys)
}
