// CountryData.swift
// GeoExplorer
//
// A single static source of truth for all world countries.
// `enum` with no cases is a common Swift trick to create a pure namespace —
// you can never accidentally create a `CountryData()` instance.

import Foundation

enum CountryData {
    // `static let` means this array is created once and shared everywhere.
    static let all: [Country] = [

        // MARK: - Africa
        Country(name: "Algeria",                    capital: "Algiers",               continent: "Africa",   flag: "🇩🇿"),
        Country(name: "Angola",                     capital: "Luanda",                continent: "Africa",   flag: "🇦🇴"),
        Country(name: "Benin",                      capital: "Porto-Novo",            continent: "Africa",   flag: "🇧🇯"),
        Country(name: "Botswana",                   capital: "Gaborone",              continent: "Africa",   flag: "🇧🇼"),
        Country(name: "Burkina Faso",               capital: "Ouagadougou",           continent: "Africa",   flag: "🇧🇫"),
        Country(name: "Burundi",                    capital: "Gitega",                continent: "Africa",   flag: "🇧🇮"),
        Country(name: "Cameroon",                   capital: "Yaoundé",               continent: "Africa",   flag: "🇨🇲"),
        Country(name: "Cape Verde",                 capital: "Praia",                 continent: "Africa",   flag: "🇨🇻"),
        Country(name: "Central African Republic",   capital: "Bangui",                continent: "Africa",   flag: "🇨🇫"),
        Country(name: "Chad",                       capital: "N'Djamena",             continent: "Africa",   flag: "🇹🇩"),
        Country(name: "Comoros",                    capital: "Moroni",                continent: "Africa",   flag: "🇰🇲"),
        Country(name: "Democratic Republic of Congo", capital: "Kinshasa",            continent: "Africa",   flag: "🇨🇩"),
        Country(name: "Republic of Congo",          capital: "Brazzaville",           continent: "Africa",   flag: "🇨🇬"),
        Country(name: "Djibouti",                   capital: "Djibouti",              continent: "Africa",   flag: "🇩🇯"),
        Country(name: "Egypt",                      capital: "Cairo",                 continent: "Africa",   flag: "🇪🇬"),
        Country(name: "Equatorial Guinea",          capital: "Malabo",                continent: "Africa",   flag: "🇬🇶"),
        Country(name: "Eritrea",                    capital: "Asmara",                continent: "Africa",   flag: "🇪🇷"),
        Country(name: "Eswatini",                   capital: "Mbabane",               continent: "Africa",   flag: "🇸🇿"),
        Country(name: "Ethiopia",                   capital: "Addis Ababa",           continent: "Africa",   flag: "🇪🇹"),
        Country(name: "Gabon",                      capital: "Libreville",            continent: "Africa",   flag: "🇬🇦"),
        Country(name: "Gambia",                     capital: "Banjul",                continent: "Africa",   flag: "🇬🇲"),
        Country(name: "Ghana",                      capital: "Accra",                 continent: "Africa",   flag: "🇬🇭"),
        Country(name: "Guinea",                     capital: "Conakry",               continent: "Africa",   flag: "🇬🇳"),
        Country(name: "Guinea-Bissau",              capital: "Bissau",                continent: "Africa",   flag: "🇬🇼"),
        Country(name: "Ivory Coast",                capital: "Yamoussoukro",          continent: "Africa",   flag: "🇨🇮"),
        Country(name: "Kenya",                      capital: "Nairobi",               continent: "Africa",   flag: "🇰🇪"),
        Country(name: "Lesotho",                    capital: "Maseru",                continent: "Africa",   flag: "🇱🇸"),
        Country(name: "Liberia",                    capital: "Monrovia",              continent: "Africa",   flag: "🇱🇷"),
        Country(name: "Libya",                      capital: "Tripoli",               continent: "Africa",   flag: "🇱🇾"),
        Country(name: "Madagascar",                 capital: "Antananarivo",          continent: "Africa",   flag: "🇲🇬"),
        Country(name: "Malawi",                     capital: "Lilongwe",              continent: "Africa",   flag: "🇲🇼"),
        Country(name: "Mali",                       capital: "Bamako",                continent: "Africa",   flag: "🇲🇱"),
        Country(name: "Mauritania",                 capital: "Nouakchott",            continent: "Africa",   flag: "🇲🇷"),
        Country(name: "Mauritius",                  capital: "Port Louis",            continent: "Africa",   flag: "🇲🇺"),
        Country(name: "Morocco",                    capital: "Rabat",                 continent: "Africa",   flag: "🇲🇦"),
        Country(name: "Mozambique",                 capital: "Maputo",                continent: "Africa",   flag: "🇲🇿"),
        Country(name: "Namibia",                    capital: "Windhoek",              continent: "Africa",   flag: "🇳🇦"),
        Country(name: "Niger",                      capital: "Niamey",                continent: "Africa",   flag: "🇳🇪"),
        Country(name: "Nigeria",                    capital: "Abuja",                 continent: "Africa",   flag: "🇳🇬"),
        Country(name: "Rwanda",                     capital: "Kigali",                continent: "Africa",   flag: "🇷🇼"),
        Country(name: "São Tomé and Príncipe",      capital: "São Tomé",              continent: "Africa",   flag: "🇸🇹"),
        Country(name: "Senegal",                    capital: "Dakar",                 continent: "Africa",   flag: "🇸🇳"),
        Country(name: "Seychelles",                 capital: "Victoria",              continent: "Africa",   flag: "🇸🇨"),
        Country(name: "Sierra Leone",               capital: "Freetown",              continent: "Africa",   flag: "🇸🇱"),
        Country(name: "Somalia",                    capital: "Mogadishu",             continent: "Africa",   flag: "🇸🇴"),
        Country(name: "South Africa",               capital: "Pretoria",              continent: "Africa",   flag: "🇿🇦"),
        Country(name: "South Sudan",                capital: "Juba",                  continent: "Africa",   flag: "🇸🇸"),
        Country(name: "Sudan",                      capital: "Khartoum",              continent: "Africa",   flag: "🇸🇩"),
        Country(name: "Tanzania",                   capital: "Dodoma",                continent: "Africa",   flag: "🇹🇿"),
        Country(name: "Togo",                       capital: "Lomé",                  continent: "Africa",   flag: "🇹🇬"),
        Country(name: "Tunisia",                    capital: "Tunis",                 continent: "Africa",   flag: "🇹🇳"),
        Country(name: "Uganda",                     capital: "Kampala",               continent: "Africa",   flag: "🇺🇬"),
        Country(name: "Zambia",                     capital: "Lusaka",                continent: "Africa",   flag: "🇿🇲"),
        Country(name: "Zimbabwe",                   capital: "Harare",                continent: "Africa",   flag: "🇿🇼"),

        // MARK: - Americas
        Country(name: "Antigua and Barbuda",        capital: "Saint John's",          continent: "Americas", flag: "🇦🇬"),
        Country(name: "Argentina",                  capital: "Buenos Aires",          continent: "Americas", flag: "🇦🇷"),
        Country(name: "Bahamas",                    capital: "Nassau",                continent: "Americas", flag: "🇧🇸"),
        Country(name: "Barbados",                   capital: "Bridgetown",            continent: "Americas", flag: "🇧🇧"),
        Country(name: "Belize",                     capital: "Belmopan",              continent: "Americas", flag: "🇧🇿"),
        Country(name: "Bolivia",                    capital: "Sucre",                 continent: "Americas", flag: "🇧🇴"),
        Country(name: "Brazil",                     capital: "Brasília",              continent: "Americas", flag: "🇧🇷"),
        Country(name: "Canada",                     capital: "Ottawa",                continent: "Americas", flag: "🇨🇦"),
        Country(name: "Chile",                      capital: "Santiago",              continent: "Americas", flag: "🇨🇱"),
        Country(name: "Colombia",                   capital: "Bogotá",                continent: "Americas", flag: "🇨🇴"),
        Country(name: "Costa Rica",                 capital: "San José",              continent: "Americas", flag: "🇨🇷"),
        Country(name: "Cuba",                       capital: "Havana",                continent: "Americas", flag: "🇨🇺"),
        Country(name: "Dominica",                   capital: "Roseau",                continent: "Americas", flag: "🇩🇲"),
        Country(name: "Dominican Republic",         capital: "Santo Domingo",         continent: "Americas", flag: "🇩🇴"),
        Country(name: "Ecuador",                    capital: "Quito",                 continent: "Americas", flag: "🇪🇨"),
        Country(name: "El Salvador",                capital: "San Salvador",          continent: "Americas", flag: "🇸🇻"),
        Country(name: "Grenada",                    capital: "Saint George's",        continent: "Americas", flag: "🇬🇩"),
        Country(name: "Guatemala",                  capital: "Guatemala City",        continent: "Americas", flag: "🇬🇹"),
        Country(name: "Guyana",                     capital: "Georgetown",            continent: "Americas", flag: "🇬🇾"),
        Country(name: "Haiti",                      capital: "Port-au-Prince",        continent: "Americas", flag: "🇭🇹"),
        Country(name: "Honduras",                   capital: "Tegucigalpa",           continent: "Americas", flag: "🇭🇳"),
        Country(name: "Jamaica",                    capital: "Kingston",              continent: "Americas", flag: "🇯🇲"),
        Country(name: "Mexico",                     capital: "Mexico City",           continent: "Americas", flag: "🇲🇽"),
        Country(name: "Nicaragua",                  capital: "Managua",               continent: "Americas", flag: "🇳🇮"),
        Country(name: "Panama",                     capital: "Panama City",           continent: "Americas", flag: "🇵🇦"),
        Country(name: "Paraguay",                   capital: "Asunción",              continent: "Americas", flag: "🇵🇾"),
        Country(name: "Peru",                       capital: "Lima",                  continent: "Americas", flag: "🇵🇪"),
        Country(name: "Saint Kitts and Nevis",      capital: "Basseterre",            continent: "Americas", flag: "🇰🇳"),
        Country(name: "Saint Lucia",                capital: "Castries",              continent: "Americas", flag: "🇱🇨"),
        Country(name: "Saint Vincent and the Grenadines", capital: "Kingstown",      continent: "Americas", flag: "🇻🇨"),
        Country(name: "Suriname",                   capital: "Paramaribo",            continent: "Americas", flag: "🇸🇷"),
        Country(name: "Trinidad and Tobago",        capital: "Port of Spain",         continent: "Americas", flag: "🇹🇹"),
        Country(name: "United States",              capital: "Washington, D.C.",      continent: "Americas", flag: "🇺🇸"),
        Country(name: "Uruguay",                    capital: "Montevideo",            continent: "Americas", flag: "🇺🇾"),
        Country(name: "Venezuela",                  capital: "Caracas",               continent: "Americas", flag: "🇻🇪"),

        // MARK: - Asia
        Country(name: "Afghanistan",                capital: "Kabul",                 continent: "Asia",     flag: "🇦🇫"),
        Country(name: "Armenia",                    capital: "Yerevan",               continent: "Asia",     flag: "🇦🇲"),
        Country(name: "Azerbaijan",                 capital: "Baku",                  continent: "Asia",     flag: "🇦🇿"),
        Country(name: "Bahrain",                    capital: "Manama",                continent: "Asia",     flag: "🇧🇭"),
        Country(name: "Bangladesh",                 capital: "Dhaka",                 continent: "Asia",     flag: "🇧🇩"),
        Country(name: "Bhutan",                     capital: "Thimphu",               continent: "Asia",     flag: "🇧🇹"),
        Country(name: "Brunei",                     capital: "Bandar Seri Begawan",   continent: "Asia",     flag: "🇧🇳"),
        Country(name: "Cambodia",                   capital: "Phnom Penh",            continent: "Asia",     flag: "🇰🇭"),
        Country(name: "China",                      capital: "Beijing",               continent: "Asia",     flag: "🇨🇳"),
        Country(name: "Cyprus",                     capital: "Nicosia",               continent: "Asia",     flag: "🇨🇾"),
        Country(name: "Georgia",                    capital: "Tbilisi",               continent: "Asia",     flag: "🇬🇪"),
        Country(name: "India",                      capital: "New Delhi",             continent: "Asia",     flag: "🇮🇳"),
        Country(name: "Indonesia",                  capital: "Jakarta",               continent: "Asia",     flag: "🇮🇩"),
        Country(name: "Iran",                       capital: "Tehran",                continent: "Asia",     flag: "🇮🇷"),
        Country(name: "Iraq",                       capital: "Baghdad",               continent: "Asia",     flag: "🇮🇶"),
        Country(name: "Israel",                     capital: "Jerusalem",             continent: "Asia",     flag: "🇮🇱"),
        Country(name: "Japan",                      capital: "Tokyo",                 continent: "Asia",     flag: "🇯🇵"),
        Country(name: "Jordan",                     capital: "Amman",                 continent: "Asia",     flag: "🇯🇴"),
        Country(name: "Kazakhstan",                 capital: "Astana",                continent: "Asia",     flag: "🇰🇿"),
        Country(name: "Kuwait",                     capital: "Kuwait City",           continent: "Asia",     flag: "🇰🇼"),
        Country(name: "Kyrgyzstan",                 capital: "Bishkek",               continent: "Asia",     flag: "🇰🇬"),
        Country(name: "Laos",                       capital: "Vientiane",             continent: "Asia",     flag: "🇱🇦"),
        Country(name: "Lebanon",                    capital: "Beirut",                continent: "Asia",     flag: "🇱🇧"),
        Country(name: "Malaysia",                   capital: "Kuala Lumpur",          continent: "Asia",     flag: "🇲🇾"),
        Country(name: "Maldives",                   capital: "Malé",                  continent: "Asia",     flag: "🇲🇻"),
        Country(name: "Mongolia",                   capital: "Ulaanbaatar",           continent: "Asia",     flag: "🇲🇳"),
        Country(name: "Myanmar",                    capital: "Naypyidaw",             continent: "Asia",     flag: "🇲🇲"),
        Country(name: "Nepal",                      capital: "Kathmandu",             continent: "Asia",     flag: "🇳🇵"),
        Country(name: "North Korea",                capital: "Pyongyang",             continent: "Asia",     flag: "🇰🇵"),
        Country(name: "Oman",                       capital: "Muscat",                continent: "Asia",     flag: "🇴🇲"),
        Country(name: "Pakistan",                   capital: "Islamabad",             continent: "Asia",     flag: "🇵🇰"),
        Country(name: "Palestine",                  capital: "Ramallah",              continent: "Asia",     flag: "🇵🇸"),
        Country(name: "Philippines",                capital: "Manila",                continent: "Asia",     flag: "🇵🇭"),
        Country(name: "Qatar",                      capital: "Doha",                  continent: "Asia",     flag: "🇶🇦"),
        Country(name: "Saudi Arabia",               capital: "Riyadh",                continent: "Asia",     flag: "🇸🇦"),
        Country(name: "Singapore",                  capital: "Singapore",             continent: "Asia",     flag: "🇸🇬"),
        Country(name: "South Korea",                capital: "Seoul",                 continent: "Asia",     flag: "🇰🇷"),
        Country(name: "Sri Lanka",                  capital: "Sri Jayawardenepura Kotte", continent: "Asia", flag: "🇱🇰"),
        Country(name: "Syria",                      capital: "Damascus",              continent: "Asia",     flag: "🇸🇾"),
        Country(name: "Taiwan",                     capital: "Taipei",                continent: "Asia",     flag: "🇹🇼"),
        Country(name: "Tajikistan",                 capital: "Dushanbe",              continent: "Asia",     flag: "🇹🇯"),
        Country(name: "Thailand",                   capital: "Bangkok",               continent: "Asia",     flag: "🇹🇭"),
        Country(name: "Timor-Leste",                capital: "Dili",                  continent: "Asia",     flag: "🇹🇱"),
        Country(name: "Turkey",                     capital: "Ankara",                continent: "Asia",     flag: "🇹🇷"),
        Country(name: "Turkmenistan",               capital: "Ashgabat",              continent: "Asia",     flag: "🇹🇲"),
        Country(name: "United Arab Emirates",       capital: "Abu Dhabi",             continent: "Asia",     flag: "🇦🇪"),
        Country(name: "Uzbekistan",                 capital: "Tashkent",              continent: "Asia",     flag: "🇺🇿"),
        Country(name: "Vietnam",                    capital: "Hanoi",                 continent: "Asia",     flag: "🇻🇳"),
        Country(name: "Yemen",                      capital: "Sana'a",                continent: "Asia",     flag: "🇾🇪"),

        // MARK: - Europe
        Country(name: "Albania",                    capital: "Tirana",                continent: "Europe",   flag: "🇦🇱"),
        Country(name: "Andorra",                    capital: "Andorra la Vella",      continent: "Europe",   flag: "🇦🇩"),
        Country(name: "Austria",                    capital: "Vienna",                continent: "Europe",   flag: "🇦🇹"),
        Country(name: "Belarus",                    capital: "Minsk",                 continent: "Europe",   flag: "🇧🇾"),
        Country(name: "Belgium",                    capital: "Brussels",              continent: "Europe",   flag: "🇧🇪"),
        Country(name: "Bosnia and Herzegovina",     capital: "Sarajevo",              continent: "Europe",   flag: "🇧🇦"),
        Country(name: "Bulgaria",                   capital: "Sofia",                 continent: "Europe",   flag: "🇧🇬"),
        Country(name: "Croatia",                    capital: "Zagreb",                continent: "Europe",   flag: "🇭🇷"),
        Country(name: "Czech Republic",             capital: "Prague",                continent: "Europe",   flag: "🇨🇿"),
        Country(name: "Denmark",                    capital: "Copenhagen",            continent: "Europe",   flag: "🇩🇰"),
        Country(name: "Estonia",                    capital: "Tallinn",               continent: "Europe",   flag: "🇪🇪"),
        Country(name: "Finland",                    capital: "Helsinki",              continent: "Europe",   flag: "🇫🇮"),
        Country(name: "France",                     capital: "Paris",                 continent: "Europe",   flag: "🇫🇷"),
        Country(name: "Germany",                    capital: "Berlin",                continent: "Europe",   flag: "🇩🇪"),
        Country(name: "Greece",                     capital: "Athens",                continent: "Europe",   flag: "🇬🇷"),
        Country(name: "Hungary",                    capital: "Budapest",              continent: "Europe",   flag: "🇭🇺"),
        Country(name: "Iceland",                    capital: "Reykjavík",             continent: "Europe",   flag: "🇮🇸"),
        Country(name: "Ireland",                    capital: "Dublin",                continent: "Europe",   flag: "🇮🇪"),
        Country(name: "Italy",                      capital: "Rome",                  continent: "Europe",   flag: "🇮🇹"),
        Country(name: "Kosovo",                     capital: "Pristina",              continent: "Europe",   flag: "🇽🇰"),
        Country(name: "Latvia",                     capital: "Riga",                  continent: "Europe",   flag: "🇱🇻"),
        Country(name: "Liechtenstein",              capital: "Vaduz",                 continent: "Europe",   flag: "🇱🇮"),
        Country(name: "Lithuania",                  capital: "Vilnius",               continent: "Europe",   flag: "🇱🇹"),
        Country(name: "Luxembourg",                 capital: "Luxembourg City",       continent: "Europe",   flag: "🇱🇺"),
        Country(name: "Malta",                      capital: "Valletta",              continent: "Europe",   flag: "🇲🇹"),
        Country(name: "Moldova",                    capital: "Chișinău",              continent: "Europe",   flag: "🇲🇩"),
        Country(name: "Monaco",                     capital: "Monaco",                continent: "Europe",   flag: "🇲🇨"),
        Country(name: "Montenegro",                 capital: "Podgorica",             continent: "Europe",   flag: "🇲🇪"),
        Country(name: "Netherlands",                capital: "Amsterdam",             continent: "Europe",   flag: "🇳🇱"),
        Country(name: "North Macedonia",            capital: "Skopje",                continent: "Europe",   flag: "🇲🇰"),
        Country(name: "Norway",                     capital: "Oslo",                  continent: "Europe",   flag: "🇳🇴"),
        Country(name: "Poland",                     capital: "Warsaw",                continent: "Europe",   flag: "🇵🇱"),
        Country(name: "Portugal",                   capital: "Lisbon",                continent: "Europe",   flag: "🇵🇹"),
        Country(name: "Romania",                    capital: "Bucharest",             continent: "Europe",   flag: "🇷🇴"),
        Country(name: "Russia",                     capital: "Moscow",                continent: "Europe",   flag: "🇷🇺"),
        Country(name: "San Marino",                 capital: "San Marino",            continent: "Europe",   flag: "🇸🇲"),
        Country(name: "Serbia",                     capital: "Belgrade",              continent: "Europe",   flag: "🇷🇸"),
        Country(name: "Slovakia",                   capital: "Bratislava",            continent: "Europe",   flag: "🇸🇰"),
        Country(name: "Slovenia",                   capital: "Ljubljana",             continent: "Europe",   flag: "🇸🇮"),
        Country(name: "Spain",                      capital: "Madrid",                continent: "Europe",   flag: "🇪🇸"),
        Country(name: "Sweden",                     capital: "Stockholm",             continent: "Europe",   flag: "🇸🇪"),
        Country(name: "Switzerland",                capital: "Bern",                  continent: "Europe",   flag: "🇨🇭"),
        Country(name: "Ukraine",                    capital: "Kyiv",                  continent: "Europe",   flag: "🇺🇦"),
        Country(name: "United Kingdom",             capital: "London",                continent: "Europe",   flag: "🇬🇧"),
        Country(name: "Vatican City",               capital: "Vatican City",          continent: "Europe",   flag: "🇻🇦"),

        // MARK: - Oceania
        Country(name: "Australia",                  capital: "Canberra",              continent: "Oceania",  flag: "🇦🇺"),
        Country(name: "Fiji",                       capital: "Suva",                  continent: "Oceania",  flag: "🇫🇯"),
        Country(name: "Kiribati",                   capital: "South Tarawa",          continent: "Oceania",  flag: "🇰🇮"),
        Country(name: "Marshall Islands",           capital: "Majuro",                continent: "Oceania",  flag: "🇲🇭"),
        Country(name: "Micronesia",                 capital: "Palikir",               continent: "Oceania",  flag: "🇫🇲"),
        Country(name: "Nauru",                      capital: "Yaren",                 continent: "Oceania",  flag: "🇳🇷"),
        Country(name: "New Zealand",                capital: "Wellington",            continent: "Oceania",  flag: "🇳🇿"),
        Country(name: "Palau",                      capital: "Ngerulmud",             continent: "Oceania",  flag: "🇵🇼"),
        Country(name: "Papua New Guinea",           capital: "Port Moresby",          continent: "Oceania",  flag: "🇵🇬"),
        Country(name: "Samoa",                      capital: "Apia",                  continent: "Oceania",  flag: "🇼🇸"),
        Country(name: "Solomon Islands",            capital: "Honiara",               continent: "Oceania",  flag: "🇸🇧"),
        Country(name: "Tonga",                      capital: "Nukuʻalofa",            continent: "Oceania",  flag: "🇹🇴"),
        Country(name: "Tuvalu",                     capital: "Funafuti",              continent: "Oceania",  flag: "🇹🇻"),
        Country(name: "Vanuatu",                    capital: "Port Vila",             continent: "Oceania",  flag: "🇻🇺"),
    ]
}
